blank_issues_enabled: true
contact_links:
  - name: OS works report
    url: https://github.com/minodisk/riffle/discussions/286
    about: Riffle works on your OS? Let us know here.
  - name: Camera works report
    url: https://github.com/minodisk/riffle/discussions/287
    about: Riffle works with your camera? Let us know here.
  - name: Software works report
    url: https://github.com/minodisk/riffle/discussions/288
    about: Riffle's judgements show up correctly in your software? Let us know here.
